### ISSUE TITLE
ลองใช้กับ landingi แล้วเจอปัญหา zipcode of undefined

### ISSUE THREAD

**Issue by boodeveloper** [earthchie/jquery.Thailand.js#45]
![thai_address_zipcode](https://user-images.githubusercontent.com/20768065/80077838-3fbad500-8578-11ea-9614-33991a2a5691.png)

**Comment by earthchie** [comment]
ขอดู url ของเว็บหน่อยครับ

**Comment by boodeveloper** [comment]
https://page.futureskill.co/datascienceoxy

**Comment by boodeveloper** [comment]
อันนี้เกิดจากอะไรหรอครับ

ส่วน เหมือนว่า CSS มันจะถูกเรียกมาทีหลัง ทำให้หน้าข้อมูลไม่แสดงหน้าตาเลย

กำลังงม ๆ หาที่แทรกใน landingi อยู่ครับ

**Comment by earthchie** [comment]
เอาทีละเรื่องนะครับ 


ก่อนอื่นเลย CSS 
https://styles.assets-landingi.com/ixBQXIJu/base.css
บรรทัดที่ 911

```css
#km5ZaPEL340TstTFdybWLnVyORTKIcu8 .widget-container { padding-top:3px;padding-left:0;padding-right:0;padding-bottom:3px;width:100%;font-size:0px;height:auto; }
```

มันไปสั่งให้ `font-size: 0;` ดังนั้นจึงไม่มีการแสดงข้อมูลครับ 

ส่วน error อื่นๆ ดูเหมือน typeahead.js จะโดนกวนจากสคริปต์อื่น ลองสลับลำดับให้มันโหลดท้ายสุดดูนะครับ
ซึ่งในส่วนนี้ผมช่วยได้ไม่มาก เนื่องจากไม่เกี่ยวกับ repo นี้ ตามที่เห็นใน stack trace นี้ครับ

![image](https://user-images.githubusercontent.com/7013039/80097942-49ebcc00-8596-11ea-973b-c9d4ac92f261.png)
